name: CI

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  scalafmt:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - name: scalafmt
        run: sbt 'scalafmtCheckAll' # https://scalameta.org/scalafmt/docs/installation.html#task-keys

  scalafix:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - name: scalafix
        run: sbt 'scalafixAll --check' # https://scalacenter.github.io/scalafix/docs/users/installation.html#enforce-in-ci

  unit-tests:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - name: Run tests
        shell: bash
        run: sbt test
