name: Launch Scala Steward

# This workflow will launch everyday at 00:00
on:
  schedule:
    - cron: '0 0 * * 1-5'
  workflow_dispatch: {}

jobs:
  scala-steward:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    env:
      GH_READ_PACKAGES: ${{ secrets.GH_READ_PACKAGES }}
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2.54.0
        with:
          github-token: ${{ secrets.SCALA_STEWARD }}